/* =========================================================================
   MY HEALTH — product.js  (tomar book.js pattern)
   -------------------------------------------------------------------------
   PORE EDIT KORAR GUIDE:
   • price / oldPrice  -> taka change koro (number, ৳ chara)
   • img               -> nijer real product photo dile ekhane URL boshao,
                          jemon  img:"images/whey.jpg"  ba online URL.
                          Ekhon placeholder SVG ase (images/pID.svg).
   • name, desc, benefits, use, rating, reviews, tags -> jemon dorkar change koro
   NOTE: ei file ta app.js er AGE load hoy (HTML e script order).
   ========================================================================= */

const PRODUCTS = [
  { id:1, img:"https://images.pexels.com/photos/13787566/pexels-photo-13787566.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Whey Protein Isolate 2kg — Chocolate", goal:"muscle", emoji:"🥤", timing:"postworkout",
    rating:4.8, reviews:412, oldPrice:5200, price:3400, stock:true, tags:["flash","best"], brand:"NutriPro", size:"2 kg · 66 servings",
    desc:"Fast-absorbing 100% whey isolate with 27g protein per scoop. Low in carbs and sugar — ideal for lean muscle building and post-workout recovery.",
    benefits:["27g protein per serving","Supports muscle recovery & growth","Low carb, low sugar","Mixes easily, no clumps"],
    use:{dose:"1 scoop (30g) with 250ml water/milk", when:"Within 30 min after workout", duration:"Daily"} },

  { id:2, img:"https://images.pexels.com/photos/13787561/pexels-photo-13787561.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Vitamin C 1000mg with Zinc, 60 Tablets", goal:"immunity", emoji:"🍊", timing:"morning",
    rating:4.7, reviews:289, oldPrice:850, price:599, stock:true, tags:["best"], brand:"VitaLife", size:"60 tablets",
    desc:"High-strength Vitamin C with Zinc to support your immune system, skin health and natural defense — especially during seasonal changes.",
    benefits:["Boosts immune defense","Antioxidant support","Zinc for faster recovery","One-a-day dosing"],
    use:{dose:"1 tablet daily", when:"After breakfast", duration:"Ongoing"} },

  { id:3, img:"https://images.pexels.com/photos/13779107/pexels-photo-13779107.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Omega-3 Fish Oil 1000mg, 120 Softgels", goal:"brain", emoji:"🐟", timing:"anytime",
    rating:4.9, reviews:531, oldPrice:1800, price:1290, stock:true, tags:["best","flash"], brand:"OceanPure", size:"120 softgels",
    desc:"Premium fish oil rich in EPA & DHA for heart, brain and joint health. Molecularly distilled for purity, no fishy aftertaste.",
    benefits:["Supports heart & brain","EPA + DHA omega-3","Joint & eye health","Purified, no fishy burp"],
    use:{dose:"1–2 softgels daily", when:"With a meal", duration:"Ongoing"} },

  { id:4, img:"https://images.pexels.com/photos/11361813/pexels-photo-11361813.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Magnesium Glycinate 400mg, 90 Capsules", goal:"sleep", emoji:"🌿", timing:"night",
    rating:4.6, reviews:174, oldPrice:1400, price:990, stock:true, tags:["new"], brand:"CalmWell", size:"90 capsules",
    desc:"Highly absorbable magnesium glycinate to relax muscles, ease stress and promote deeper, more restful sleep.",
    benefits:["Promotes relaxation & sleep","Eases muscle cramps","Gentle on stomach","Supports nervous system"],
    use:{dose:"2 capsules", when:"30–60 min before bed", duration:"Daily"} },

  { id:5, img:"https://images.pexels.com/photos/14433552/pexels-photo-14433552.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"BCAA 2:1:1 Energy Powder — Mango, 30 Serv", goal:"muscle", emoji:"🥭", timing:"postworkout",
    rating:4.5, reviews:98, oldPrice:2200, price:1650, stock:true, tags:["flash"], brand:"NutriPro", size:"300g · 30 servings",
    desc:"Branched-chain amino acids in the ideal 2:1:1 ratio to reduce muscle breakdown, fight fatigue and speed up recovery.",
    benefits:["Reduces muscle fatigue","Faster recovery","Refreshing mango flavor","Sugar-free"],
    use:{dose:"1 scoop with 300ml water", when:"During / after workout", duration:"Training days"} },

  { id:6, img:"https://images.pexels.com/photos/13787566/pexels-photo-13787566.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Vitamin D3 2000 IU, 120 Softgels", goal:"bones", emoji:"☀️", timing:"morning",
    rating:4.8, reviews:362, oldPrice:900, price:650, stock:true, tags:["best"], brand:"VitaLife", size:"120 softgels",
    desc:"Sunshine vitamin for strong bones, immunity and mood. Essential for anyone with limited sun exposure.",
    benefits:["Strengthens bones & teeth","Supports immunity","Improves mood","Aids calcium absorption"],
    use:{dose:"1 softgel daily", when:"With a meal", duration:"Ongoing"} },

  { id:7, img:"https://images.pexels.com/photos/13787561/pexels-photo-13787561.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Ashwagandha KSM-66 600mg, 90 Caps", goal:"sleep", emoji:"🌱", timing:"night",
    rating:4.7, reviews:245, oldPrice:1600, price:1150, stock:true, tags:["best","new"], brand:"HerbRoot", size:"90 capsules",
    desc:"Clinically-studied KSM-66 ashwagandha to lower stress, improve sleep quality and support energy & focus.",
    benefits:["Reduces stress & anxiety","Improves sleep quality","Supports stamina","Adaptogenic herb"],
    use:{dose:"1 capsule", when:"After dinner", duration:"Daily for 8+ weeks"} },

  { id:8, img:"https://images.pexels.com/photos/13779107/pexels-photo-13779107.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Multivitamin for Men, 60 Tablets", goal:"energy", emoji:"💊", timing:"morning",
    rating:4.6, reviews:201, oldPrice:1200, price:849, stock:true, tags:[], brand:"VitaLife", size:"60 tablets",
    desc:"Complete daily multivitamin with 24 essential vitamins and minerals to fill nutritional gaps and support all-day energy.",
    benefits:["24 vitamins & minerals","All-day energy support","Immunity & metabolism","Convenient one-a-day"],
    use:{dose:"1 tablet daily", when:"After breakfast", duration:"Ongoing"} },

  { id:9, img:"https://images.pexels.com/photos/11361813/pexels-photo-11361813.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Biotin 10000mcg Hair & Skin, 60 Caps", goal:"skin", emoji:"✨", timing:"anytime",
    rating:4.5, reviews:156, oldPrice:1100, price:799, stock:true, tags:["new"], brand:"GlowLab", size:"60 capsules",
    desc:"High-potency biotin to strengthen hair, support nail growth and promote healthy, glowing skin.",
    benefits:["Stronger hair & nails","Healthy glowing skin","Reduces hair fall","High 10000mcg dose"],
    use:{dose:"1 capsule daily", when:"With a meal", duration:"3+ months for best results"} },

  { id:10, img:"https://images.pexels.com/photos/14433552/pexels-photo-14433552.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Vitamin B-Complex, 100 Tablets", goal:"energy", emoji:"⚡", timing:"morning",
    rating:4.7, reviews:188, oldPrice:700, price:520, stock:true, tags:["flash"], brand:"VitaLife", size:"100 tablets",
    desc:"All 8 B vitamins in one tablet to convert food into energy, support brain function and reduce tiredness.",
    benefits:["Fights fatigue","Supports metabolism","Healthy nervous system","All 8 B-vitamins"],
    use:{dose:"1 tablet daily", when:"After breakfast", duration:"Ongoing"} },

  { id:11, img:"https://images.pexels.com/photos/13787566/pexels-photo-13787566.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Calcium + Magnesium + Zinc, 90 Tabs", goal:"bones", emoji:"🦴", timing:"anytime",
    rating:4.6, reviews:142, oldPrice:950, price:699, stock:true, tags:[], brand:"BoneStrong", size:"90 tablets",
    desc:"Triple-mineral formula for strong bones, muscle function and recovery — perfect for active adults and seniors.",
    benefits:["Strong bones & joints","Muscle function","Better mineral absorption","3-in-1 formula"],
    use:{dose:"1 tablet", when:"After dinner", duration:"Ongoing"} },

  { id:12, img:"https://images.pexels.com/photos/13787561/pexels-photo-13787561.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"L-Carnitine Fat Burner 500mg, 60 Caps", goal:"weight", emoji:"🔥", timing:"morning",
    rating:4.4, reviews:87, oldPrice:1500, price:1099, stock:true, tags:["flash"], brand:"LeanFit", size:"60 capsules",
    desc:"Helps your body turn fat into energy. Great alongside exercise for weight management and workout performance.",
    benefits:["Supports fat metabolism","Boosts workout energy","Stimulant-free","Vegetarian capsule"],
    use:{dose:"1 capsule", when:"30 min before workout", duration:"Training days"} },

  { id:13, img:"https://images.pexels.com/photos/13779107/pexels-photo-13779107.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Creatine Monohydrate 300g Micronized", goal:"muscle", emoji:"💪", timing:"postworkout",
    rating:4.9, reviews:476, oldPrice:1800, price:1290, stock:true, tags:["best"], brand:"NutriPro", size:"300g · 60 servings",
    desc:"The most researched supplement for strength and power. Micronized for easy mixing — increases muscle volume and performance.",
    benefits:["More strength & power","Increases muscle volume","100% pure creatine","Unflavored, mixes easily"],
    use:{dose:"5g (1 scoop) with water/juice", when:"Post-workout or anytime", duration:"Daily"} },

  { id:14, img:"https://images.pexels.com/photos/14433552/pexels-photo-14433552.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Elderberry + Vitamin C Immune Gummies", goal:"immunity", emoji:"🫐", timing:"anytime",
    rating:4.7, reviews:233, oldPrice:1300, price:950, stock:true, tags:["new"], brand:"VitaLife", size:"60 gummies",
    desc:"Delicious elderberry gummies packed with Vitamin C and Zinc — immune support the whole family will enjoy.",
    benefits:["Tasty immune support","Elderberry + Vit C + Zinc","Great for kids & adults","No artificial colors"],
    use:{dose:"2 gummies daily", when:"Anytime", duration:"Ongoing"} },

  { id:15, img:"https://images.pexels.com/photos/14433552/pexels-photo-14433552.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Green Tea Extract 500mg, 90 Caps", goal:"weight", emoji:"🍵", timing:"morning",
    rating:4.5, reviews:119, oldPrice:850, price:620, stock:true, tags:[], brand:"HerbRoot", size:"90 capsules",
    desc:"Concentrated green tea extract rich in EGCG antioxidants to support metabolism and natural fat burning.",
    benefits:["Supports metabolism","Rich in antioxidants","Natural energy","Supports fat loss"],
    use:{dose:"1 capsule", when:"Before meals", duration:"Daily"} },

  { id:16, img:"https://images.pexels.com/photos/13787566/pexels-photo-13787566.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Collagen Peptides Powder 250g", goal:"skin", emoji:"🌸", timing:"anytime",
    rating:4.8, reviews:301, oldPrice:2400, price:1790, stock:true, tags:["best","flash"], brand:"GlowLab", size:"250g · 25 servings",
    desc:"Hydrolyzed collagen peptides for youthful skin, stronger hair & nails, and healthy joints. Unflavored — mix into anything.",
    benefits:["Smoother, firmer skin","Stronger hair & nails","Joint support","Dissolves clear, tasteless"],
    use:{dose:"1 scoop (10g)", when:"In coffee, water or smoothie", duration:"Daily for 8+ weeks"} },

  { id:17, img:"https://images.pexels.com/photos/13787561/pexels-photo-13787561.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Probiotic 50 Billion CFU, 60 Caps", goal:"immunity", emoji:"🦠", timing:"morning",
    rating:4.6, reviews:167, oldPrice:1900, price:1450, stock:true, tags:["new"], brand:"GutWell", size:"60 capsules",
    desc:"50 billion CFU across 12 strains to balance gut flora, improve digestion and strengthen immunity.",
    benefits:["Better digestion","Gut & immune health","12 probiotic strains","Reduces bloating"],
    use:{dose:"1 capsule daily", when:"Empty stomach, morning", duration:"Ongoing"} },

  { id:18, img:"https://images.pexels.com/photos/13779107/pexels-photo-13779107.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Pre-Workout Energy — Blue Raspberry, 30 Serv", goal:"energy", emoji:"🚀", timing:"postworkout",
    rating:4.7, reviews:214, oldPrice:2500, price:1850, stock:true, tags:["flash"], brand:"NutriPro", size:"300g · 30 servings",
    desc:"Explosive energy, focus and pumps. Caffeine, beta-alanine and citrulline to power through your hardest sessions.",
    benefits:["Intense energy & focus","Better pumps","Delays fatigue","Refreshing flavor"],
    use:{dose:"1 scoop with 300ml water", when:"20 min before workout", duration:"Training days"} },

  { id:19, img:"https://images.pexels.com/photos/11361813/pexels-photo-11361813.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Mass Gainer 3kg — Banana", goal:"muscle", emoji:"🍌", timing:"postworkout",
    rating:4.5, reviews:132, oldPrice:4500, price:3200, stock:true, tags:[], brand:"NutriPro", size:"3 kg",
    desc:"High-calorie gainer with protein and complex carbs to help hard-gainers build size and strength.",
    benefits:["High calories for bulking","Protein + carbs blend","Supports weight gain","Great taste"],
    use:{dose:"2 scoops with 400ml milk", when:"After workout / between meals", duration:"Daily"} },

  { id:20, img:"https://images.pexels.com/photos/14433552/pexels-photo-14433552.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Melatonin 5mg Sleep Aid, 100 Tablets", goal:"sleep", emoji:"😴", timing:"night",
    rating:4.6, reviews:178, oldPrice:600, price:430, stock:true, tags:["best"], brand:"CalmWell", size:"100 tablets",
    desc:"Helps you fall asleep faster and reset your sleep cycle — perfect for jet lag or irregular schedules.",
    benefits:["Fall asleep faster","Resets sleep cycle","Non-habit forming","Wake refreshed"],
    use:{dose:"1 tablet", when:"30 min before bed", duration:"As needed"} },

  { id:21, img:"https://images.pexels.com/photos/13787566/pexels-photo-13787566.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Lion's Mane Mushroom 1000mg, 60 Caps", goal:"brain", emoji:"🍄", timing:"morning",
    rating:4.7, reviews:96, oldPrice:1700, price:1280, stock:true, tags:["new"], brand:"HerbRoot", size:"60 capsules",
    desc:"Nootropic mushroom traditionally used to support memory, focus and mental clarity.",
    benefits:["Supports memory & focus","Mental clarity","Nervous system support","Natural nootropic"],
    use:{dose:"1 capsule", when:"With breakfast", duration:"Daily"} },

  { id:22, img:"https://images.pexels.com/photos/13787561/pexels-photo-13787561.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Iron + Folic Acid for Women, 60 Tablets", goal:"energy", emoji:"🩸", timing:"morning",
    rating:4.5, reviews:143, oldPrice:550, price:399, stock:true, tags:[], brand:"VitaLife", size:"60 tablets",
    desc:"Gentle iron with folic acid to fight tiredness and support healthy blood — formulated for women's needs.",
    benefits:["Fights fatigue & anemia","Gentle on stomach","With folic acid","Supports energy"],
    use:{dose:"1 tablet daily", when:"After a meal", duration:"As advised"} },
  { id:23, img:"https://images.pexels.com/photos/13779107/pexels-photo-13779107.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Best Naturals TUDCA 250mg, 60 Capsules", goal:"energy", emoji:"🫀", timing:"anytime",
    rating:4.7, reviews:64, oldPrice:4550, price:4050, stock:true, tags:["new"], brand:"Best Naturals", size:"60 capsules",
    desc:"TUDCA (Tauroursodeoxycholic acid) supports healthy liver function, bile flow and cellular detox.",
    benefits:["Supports liver health", "Aids bile flow", "Cellular protection", "60 capsule supply"],
    use:{dose:"1 capsule", when:"With a meal", duration:"Daily"} },
  { id:24, img:"https://images.pexels.com/photos/11361813/pexels-photo-11361813.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Futurebiotics Vitamin K2 + D3, 120 Capsules", goal:"bones", emoji:"☀️", timing:"morning",
    rating:4.8, reviews:88, oldPrice:3650, price:3250, stock:true, tags:["new"], brand:"Futurebiotics", size:"120 capsules",
    desc:"Vitamin K2 with D3 work together for strong bones and proper calcium use in the body.",
    benefits:["Strong bones & teeth", "Supports heart health", "Better calcium absorption", "K2 + D3 combo"],
    use:{dose:"1 capsule", when:"After breakfast", duration:"Ongoing"} },
  { id:25, img:"https://images.pexels.com/photos/14433552/pexels-photo-14433552.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Life Extension Chromium 500mcg, 60 Veg Capsules", goal:"weight", emoji:"⚖️", timing:"morning",
    rating:4.6, reviews:52, oldPrice:2250, price:2050, stock:true, tags:["new"], brand:"Life Extension", size:"60 veg capsules",
    desc:"Optimized chromium helps support healthy blood sugar levels and metabolism.",
    benefits:["Supports blood sugar balance", "Aids metabolism", "Reduces cravings", "Vegetarian capsule"],
    use:{dose:"1 capsule", when:"Before a meal", duration:"Daily"} },
  { id:26, img:"https://images.pexels.com/photos/13787566/pexels-photo-13787566.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"NeoCell Super Collagen + Vitamin C & Biotin, 180 Tablets", goal:"skin", emoji:"🌸", timing:"anytime",
    rating:4.8, reviews:214, oldPrice:3450, price:3250, stock:true, tags:["new"], brand:"NeoCell", size:"180 tablets",
    desc:"Collagen with Vitamin C and Biotin for radiant skin, strong hair and healthy nails.",
    benefits:["Glowing, firmer skin", "Stronger hair & nails", "Collagen + C + Biotin", "180 tablet supply"],
    use:{dose:"3 tablets", when:"Anytime", duration:"Daily for 8+ weeks"} },
  { id:27, img:"https://images.pexels.com/photos/13787561/pexels-photo-13787561.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"NOW Foods Omega-3 Fish Oil, 200 Softgels", goal:"brain", emoji:"🐟", timing:"anytime",
    rating:4.9, reviews:331, oldPrice:3850, price:3550, stock:true, tags:["new"], brand:"NOW Foods", size:"200 softgels",
    desc:"High-quality omega-3 fish oil with EPA & DHA for heart, brain and joint health.",
    benefits:["Supports heart & brain", "EPA + DHA", "Joint & eye health", "200 softgel value pack"],
    use:{dose:"2 softgels", when:"With a meal", duration:"Ongoing"} },
  { id:28, img:"https://images.pexels.com/photos/13779107/pexels-photo-13779107.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Swanson Scottish Kelp 750mg, 30 Veggie Capsules", goal:"energy", emoji:"🌊", timing:"morning",
    rating:4.5, reviews:41, oldPrice:2050, price:1850, stock:true, tags:["new"], brand:"Swanson", size:"30 veggie capsules",
    desc:"Natural sea kelp providing iodine to support healthy thyroid function and energy.",
    benefits:["Supports thyroid", "Natural iodine source", "Boosts energy", "Organic sea kelp"],
    use:{dose:"1 capsule", when:"With breakfast", duration:"Daily"} },
  { id:29, img:"https://images.pexels.com/photos/11361813/pexels-photo-11361813.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"NOW Foods Berberine Glucose Support, 90 Softgels", goal:"weight", emoji:"🍃", timing:"morning",
    rating:4.7, reviews:96, oldPrice:5250, price:4850, stock:true, tags:["new"], brand:"NOW Foods", size:"90 softgels",
    desc:"Berberine supports healthy blood sugar, metabolism and cardiovascular wellness.",
    benefits:["Blood sugar support", "Aids metabolism", "Heart wellness", "90 softgels"],
    use:{dose:"1 softgel", when:"Before meals", duration:"Daily"} },
  { id:30, img:"https://images.pexels.com/photos/14433552/pexels-photo-14433552.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Doctor's Best PepZin GI Zinc-L-Carnosine, 120 Veg Capsules", goal:"immunity", emoji:"🛡️", timing:"morning",
    rating:4.6, reviews:73, oldPrice:4550, price:4250, stock:true, tags:["new"], brand:"Doctor's Best", size:"120 veg capsules",
    desc:"Zinc-L-Carnosine complex supports stomach lining health, digestion and immunity.",
    benefits:["Supports gut lining", "Aids digestion", "Immune support", "Vegetarian capsule"],
    use:{dose:"1 capsule", when:"Empty stomach", duration:"Daily"} },
  { id:31, img:"https://images.pexels.com/photos/13787566/pexels-photo-13787566.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Life Extension N-Acetyl-L-Cysteine (NAC) 600mg, 60 Caps", goal:"immunity", emoji:"💧", timing:"anytime",
    rating:4.7, reviews:118, oldPrice:2750, price:2650, stock:true, tags:["new"], brand:"Life Extension", size:"60 capsules",
    desc:"NAC is a powerful antioxidant that supports respiratory health, immunity and detox.",
    benefits:["Antioxidant support", "Respiratory & immune health", "Supports detox", "600mg per cap"],
    use:{dose:"1 capsule", when:"With or without food", duration:"Daily"} },
  { id:32, img:"https://images.pexels.com/photos/13787561/pexels-photo-13787561.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"NOW Foods Glutathione 500mg, 30 Veg Capsules", goal:"skin", emoji:"✨", timing:"morning",
    rating:4.6, reviews:87, oldPrice:2850, price:2550, stock:true, tags:["new"], brand:"NOW Foods", size:"30 veg capsules",
    desc:"Glutathione, the body's master antioxidant, supports skin brightness and detox.",
    benefits:["Skin brightness", "Master antioxidant", "Supports detox", "Vegetarian capsule"],
    use:{dose:"1 capsule", when:"Empty stomach", duration:"Daily"} },
  { id:33, img:"https://images.pexels.com/photos/13779107/pexels-photo-13779107.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Protocol for Life Balance Magnesium Glycinate, 180 Veg Caps", goal:"sleep", emoji:"🌙", timing:"night",
    rating:4.8, reviews:142, oldPrice:4850, price:4550, stock:true, tags:["new"], brand:"Protocol for Life Balance", size:"180 veg capsules",
    desc:"Highly absorbable magnesium glycinate to relax muscles, ease stress and improve sleep.",
    benefits:["Promotes relaxation & sleep", "Eases muscle cramps", "High absorption", "180 capsule supply"],
    use:{dose:"2 capsules", when:"Before bed", duration:"Daily"} },
  { id:34, img:"https://images.pexels.com/photos/11361813/pexels-photo-11361813.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop", name:"Nutricost Women Myo & D-Chiro Inositol, 120 Capsules", goal:"energy", emoji:"🌷", timing:"morning",
    rating:4.7, reviews:103, oldPrice:4250, price:3850, stock:true, tags:["new"], brand:"Nutricost", size:"120 capsules",
    desc:"Myo & D-Chiro Inositol in the 40:1 ratio to support women's hormonal balance and energy.",
    benefits:["Supports hormone balance", "Women's wellness", "40:1 inositol ratio", "Boosts energy"],
    use:{dose:"2 capsules", when:"Morning", duration:"Daily"} },

];